### ISSUE TITLE
This is just a question.

### ISSUE THREAD

**Issue by kyu999** [CodeBrew-io/Issues#4]
What's the difference between code brew and type safe activator?

**Comment by shmed** [comment]
We were considering doing an activator plugin in the beginning. I think one of the advantage of being totally online is that you don't have to set up anything to start programming. For example, if you want to try a short sorting algorithm, you can just open up your browser from any computer and just try it out. Even if you already had all the tools installed on your machine, it's often quicker to just open up your browser than it is to start a new project on your desktop.

**Comment by ghost** [comment]
"For example, if you want to try a short sorting algorithm, you can just open up your browser from any computer and just try it out."
Yes, it is beautiful for quickly demonstrating things to other people on their machines, for example. IMHO, the fact that all you need is just a browser to access the tool is a huge win.

**Comment by kyu999** [comment]
I got it. But I still think activator plugin is better since most developer
of scala use scala REPL in such case and it's enough for me.
Activator needs to be improved.
Anyway, thanks!

On Tue, Dec 3, 2013 at 9:20 PM, Raouf Merouche notifications@github.comwrote:

> We were considering doing an activator plugin in the beginning. I think
> one of the advantage of being totally online is that you don't have to set
> up anything to start programming. For example, if you want to try a short
> sorting algorithm, you can just open up your browser from any computer and
> just try it out. Even if you already had all the tools installed on your
> machine, it's often quicker to just open up your browser than it is to
> start a new project on your desktop.
> 
> $B!=(B
> Reply to this email directly or view it on GitHubhttps://github.com/CodeBrew-io/Issues/issues/4#issuecomment-29712792
> .

## 

$B9q:]65M\Bg3X(B
$B5W7C?r;K(B

Akita International University
Takashi Kyue

B1100574@gl.aiu.ac.jp
